"""Config/TOML writing plus the shared ``WizardFeatures`` dataclass."""
from __future__ import annotations

import sys
from dataclasses import dataclass
from pathlib import Path

import tomlkit

from archon_search._durable_io import atomic_write_bytes
from archon_search.config import SearchConfig
from archon_search.profiles import InstallProfile, get_profile

from .errors import InstallError


# ---------------------------------------------------------------------------
# WizardFeatures dataclass (Task C8-1.1)
# ---------------------------------------------------------------------------

@dataclass
class WizardFeatures:
    """Carries optional-feature choices from wizard prompt functions to config writer."""

    install_code_extra: bool = False
    install_graph_extra: bool = False
    install_multilingual_extra: bool = False
    disable_reranker: bool = False
    enable_watch: bool = False
    enable_telemetry: bool = False
    eager_load_embedders: bool = False
    # None = accepted default (key omitted from config); str = explicitly chosen (key written),
    # even when the chosen value equals the config default. Plain defaults cannot express this.
    routing_strategy: str | None = None
    log_format: str | None = None
    # C15 Tier 1 deployment flags
    host: str | None = None
    port: int | None = None
    db_path: str | None = None
    log_level: str | None = None
    top_k: int | None = None
    telemetry_retention_days: int | None = None
    # C15 Tier 2 AI query expansion flags
    enable_hyde: bool = False
    enable_rag_fusion: bool = False
    # G10 BE-8: provider-selection for HyDE / RAG Fusion
    hyde_provider: str = "anthropic"          # "anthropic" | "openai" | "ollama" | "claude_cli" | "llama_cpp"
    hyde_model: str = ""                      # empty = use provider default
    hyde_ollama_base_url: str = ""            # empty = use config default
    hyde_llama_cpp_base_url: str = ""         # empty = use config default
    rag_fusion_provider: str = "anthropic"
    rag_fusion_model: str = ""
    rag_fusion_ollama_base_url: str = ""
    rag_fusion_llama_cpp_base_url: str = ""
    # FE-2: [graph] LLM-backed enrichment provider (independent of install_graph_extra/graph.enabled)
    graph_provider: str = ""                  # "" = enrichment disabled (GraphConfig.provider stays None)
    graph_extraction_model: str = ""
    graph_llama_cpp_base_url: str = ""        # empty = use config default
    graph_ollama_base_url: str = ""           # empty = use config default


def _write_profile_config(
    config_path: Path,
    profile: InstallProfile,
    profile_name: str,
    multilingual: bool,
    features: WizardFeatures | None = None,
) -> None:
    if config_path.exists():
        doc = tomlkit.parse(config_path.read_text())
    else:
        doc = tomlkit.document()

    if "database" not in doc:
        doc.add("database", tomlkit.table())

    db = doc["database"]
    db["embedding_model"] = profile.embedder
    db["reranker_model"] = profile.reranker if profile.reranker is not None else ""
    db["chunk_size"] = profile.chunk_size
    db["profile"] = profile_name
    db["multilingual"] = multilingual

    if features is not None:
        _apply_wizard_features_to_toml(doc, features)

    tmp = config_path.with_suffix(config_path.suffix + ".tmp")
    tmp.unlink(missing_ok=True)
    atomic_write_bytes(config_path, tomlkit.dumps(doc).encode())


def _profile_toml(profile_name: str, multilingual: bool, features: WizardFeatures | None = None) -> str:
    # Delegates to _default_toml() for a complete all-sections base, then overlays
    # profile-specific [database] values via _write_profile_config logic in-memory.
    # This ensures every section generated by _default_toml() is present without
    # duplicating section-building logic here.
    from archon_search.cli.config_cmd import _default_toml  # noqa: PLC0415

    doc = tomlkit.parse(_default_toml())
    profile = get_profile(profile_name, multilingual)

    db = doc["database"]
    db["embedding_model"] = profile.embedder
    db["reranker_model"] = profile.reranker if profile.reranker is not None else ""
    db["chunk_size"] = profile.chunk_size
    db["profile"] = profile_name
    db["multilingual"] = multilingual

    if features is not None:
        _apply_wizard_features_to_toml(doc, features)

    return tomlkit.dumps(doc)


def _reconcile_ollama_base_url(section: tomlkit.items.Table, base_url: str) -> None:
    """Set or clear ``ollama_base_url`` on a config *section* table.

    The wizard mutates an existing config on re-run, so a plain conditional write
    would leak a previously-saved custom URL when the operator keeps Ollama but
    reverts the URL to the default (``base_url == ""``). Writing authoritatively —
    set a custom value, else delete any stale key so config falls back to
    ``OLLAMA_BASE_URL_DEFAULT`` — keeps the stored URL in step with that choice.

    Scope: this only runs while the section's provider is still Ollama. Clearing a
    stale Ollama block when the operator switches provider *away* (e.g. back to
    Anthropic) is broader re-run hygiene tracked separately in
    ``Documentation/Backlog/2026-07-15-140-wizard-rerun-stale-config-brief.md``.
    """
    if base_url:
        section["ollama_base_url"] = base_url
    elif "ollama_base_url" in section:
        del section["ollama_base_url"]


def _reconcile_llama_cpp_base_url(section: tomlkit.items.Table, base_url: str) -> None:
    """Set or clear ``llama_cpp_base_url`` on a config *section* table.

    Mirrors :func:`_reconcile_ollama_base_url` for the llama.cpp base URL — see
    that function's docstring for the re-run leak this prevents.
    """
    if base_url:
        section["llama_cpp_base_url"] = base_url
    elif "llama_cpp_base_url" in section:
        del section["llama_cpp_base_url"]


def _apply_wizard_features_to_toml(doc: tomlkit.TOMLDocument, features: WizardFeatures) -> None:
    """Write WizardFeatures fields to *doc* in-place.

    Only the operator's actual choices are written (20_wizard.md §"Only the
    choices you actually made are written"). For the ``bool`` fields, "a choice"
    means a non-default value: when the value matches its default the key is
    removed from the doc if it was previously set (re-run safe: a re-run that
    returns to the default removes the key the prior run wrote).
    ``routing_strategy`` and ``log_format`` are ``str | None`` instead, because a
    bare default cannot distinguish "explicitly asked for the default" from
    "never answered": ``None`` means unanswered (key removed), and any string —
    including one equal to the config default — is written.
    ``disable_reranker`` stays conditional — re-run
    safety there is provided by the profile writer, which writes the profile's
    ``reranker_model`` default *before* calling this function. Missing sections
    are created via tomlkit.table(). ``install_code_extra`` itself is
    intentionally NOT written — it controls a subprocess install, not a config
    key. ``install_graph_extra`` also controls a subprocess install, but
    additionally writes ``graph.enabled = true`` (BE-11): without it, the
    auto-installed ``[graph]`` extras are inert (C1-I-1).
    ``install_multilingual_extra`` is likewise NOT written here — unlike graph,
    the ``[database].multilingual`` key is written separately by the profile
    config writer (``_write_profile_config``/``_profile_toml``), so no overlay
    flag is needed.
    """

    def _ensure_section(name: str) -> None:
        if name not in doc:
            doc.add(name, tomlkit.table())

    def _set_or_remove(section: str, key: str, value: object, default: object) -> None:
        _ensure_section(section)  # section must exist before the elif key-lookup below
        if value != default:
            doc[section][key] = value
        elif key in doc[section]:
            del doc[section][key]

    def _set_optional(section: str, key: str, value: str | None) -> None:
        """None = unanswered (key removed); any string is written, even if it equals the default."""
        _ensure_section(section)  # section must exist before the elif key-lookup below
        if value is not None:
            doc[section][key] = value
        elif key in doc[section]:
            del doc[section][key]

    if features.disable_reranker:
        _ensure_section("database")
        doc["database"]["reranker_model"] = ""  # stays conditional — profile writer pre-fills the default

    _set_or_remove("database", "eager_load_embedders", features.eager_load_embedders, False)
    _set_or_remove("collections", "watch", features.enable_watch, False)
    _set_or_remove("telemetry", "enabled", features.enable_telemetry, False)
    # routing_strategy / log_format use a None sentinel for "accepted default" so an
    # explicitly-passed flag is written even when it equals the default value.
    _set_optional("routing", "routing_strategy", features.routing_strategy)
    _set_optional("logging", "format", features.log_format)

    # C15 Tier 1 deployment flags
    if features.host is not None:
        _ensure_section("server")
        doc["server"]["host"] = features.host

    if features.port is not None:
        _ensure_section("server")
        doc["server"]["port"] = features.port

    if features.db_path is not None:
        _ensure_section("database")
        doc["database"]["db_path"] = features.db_path

    if features.log_level is not None:
        _ensure_section("logging")
        doc["logging"]["level"] = features.log_level

    if features.top_k is not None:
        _ensure_section("database")
        doc["database"]["top_k_return"] = features.top_k
        doc["database"]["top_k_retrieve"] = max(15, 3 * features.top_k)

    if features.telemetry_retention_days is not None and features.enable_telemetry:
        _ensure_section("telemetry")
        doc["telemetry"]["retention_days"] = features.telemetry_retention_days
    elif not features.enable_telemetry and "telemetry" in doc and "retention_days" in doc["telemetry"]:
        del doc["telemetry"]["retention_days"]

    # C15 Tier 2 AI query expansion flags (G10 BE-8: provider/model/base_url)
    if features.enable_hyde:
        _ensure_section("hyde")
        doc["hyde"]["enabled"] = True
        if features.hyde_provider != "anthropic":
            doc["hyde"]["provider"] = features.hyde_provider
            if features.hyde_provider == "claude_cli":
                # Model is optional for claude_cli — a blank means "use Claude
                # Code's default", so only write it when the operator chose one.
                # Writing "" would trip config.py's non-empty guard at startup.
                if features.hyde_model:
                    doc["hyde"]["model"] = features.hyde_model
            else:
                # Always write model for ollama/openai (even empty string) so
                # config.py's "if not model: raise ConfigError" guard fires at
                # startup when the operator left the model prompt blank.
                doc["hyde"]["model"] = features.hyde_model
                if features.hyde_provider == "ollama":
                    _reconcile_ollama_base_url(doc["hyde"], features.hyde_ollama_base_url)
                elif features.hyde_provider == "llama_cpp":
                    _reconcile_llama_cpp_base_url(doc["hyde"], features.hyde_llama_cpp_base_url)
    else:
        _ensure_section("hyde")
        doc["hyde"]["enabled"] = False

    if features.enable_rag_fusion:
        _ensure_section("rag_fusion")
        doc["rag_fusion"]["enabled"] = True
        if features.rag_fusion_provider != "anthropic":
            doc["rag_fusion"]["provider"] = features.rag_fusion_provider
            if features.rag_fusion_provider == "claude_cli":
                # Model is optional for claude_cli — a blank means "use Claude
                # Code's default", so only write it when the operator chose one.
                if features.rag_fusion_model:
                    doc["rag_fusion"]["model"] = features.rag_fusion_model
            else:
                # Always write model for ollama/openai (even empty string) so
                # config.py's "if not model: raise ConfigError" guard fires at startup.
                doc["rag_fusion"]["model"] = features.rag_fusion_model
                if features.rag_fusion_provider == "ollama":
                    _reconcile_ollama_base_url(doc["rag_fusion"], features.rag_fusion_ollama_base_url)
                elif features.rag_fusion_provider == "llama_cpp":
                    _reconcile_llama_cpp_base_url(doc["rag_fusion"], features.rag_fusion_llama_cpp_base_url)
    else:
        _ensure_section("rag_fusion")
        doc["rag_fusion"]["enabled"] = False

    # FE-2: LLM-backed graph enrichment provider — independent of graph.enabled
    # (BE-11, below): `[graph].provider` is itself the enrichment gate (no
    # separate `enabled` key), so nothing is written when the operator declined.
    if features.graph_provider:
        _ensure_section("graph")
        doc["graph"]["provider"] = features.graph_provider
        doc["graph"]["extraction_model"] = features.graph_extraction_model
        if features.graph_provider == "llama_cpp":
            _reconcile_llama_cpp_base_url(doc["graph"], features.graph_llama_cpp_base_url)
        elif features.graph_provider == "ollama":
            _reconcile_ollama_base_url(doc["graph"], features.graph_ollama_base_url)

    # BE-11: [graph] enabled must be written whenever the [graph] extras were
    # auto-installed, or the install is inert — see C1-I-1 / C1-A-4.
    if features.install_graph_extra:
        _ensure_section("graph")
        doc["graph"]["enabled"] = True


# ---------------------------------------------------------------------------
# Hand-edit detection (Task C14-5.4)
# ---------------------------------------------------------------------------

def _detect_config_hand_edits(
    config_path: Path,
    prev_profile_name: str,
    prev_multilingual: bool,
) -> bool:
    """Return True if the on-disk config has values that differ from wizard defaults.

    Compares only wizard-written keys (union of _write_profile_config and
    _apply_wizard_features_to_toml output). Returns True (always warn) if
    prev_profile_name is not a recognized profile name.
    """
    # Unknown profile — always warn
    try:
        profile = get_profile(prev_profile_name, prev_multilingual)
    except ValueError:
        return True

    # Read the on-disk config
    doc = tomlkit.parse(config_path.read_text())
    db = doc.get("database", {})

    # Compare [database] wizard-written keys against profile defaults
    expected_reranker = profile.reranker if profile.reranker is not None else ""
    if db.get("embedding_model") != profile.embedder:
        return True
    if db.get("reranker_model") != expected_reranker:
        return True
    if db.get("chunk_size") != profile.chunk_size:
        return True
    if db.get("profile") != prev_profile_name:
        return True
    if db.get("multilingual") != prev_multilingual:
        return True

    # Compare optional-feature keys against WizardFeatures() static defaults
    # Absent key = static default in effect — NOT a hand-edit.
    # Only a key that is PRESENT and DIFFERENT from the static default counts.
    defaults = WizardFeatures()
    # routing_strategy/log_format hold the None sentinel on WizardFeatures, so the real
    # default values come from SearchConfig (the single source of truth for both keys).
    config_defaults = SearchConfig()

    # eager_load_embedders (in [database])
    if "eager_load_embedders" in db and db["eager_load_embedders"] != defaults.eager_load_embedders:
        return True

    # collections.watch
    collections = doc.get("collections", {})
    if "watch" in collections and collections["watch"] != defaults.enable_watch:
        return True

    # telemetry.enabled
    telemetry = doc.get("telemetry", {})
    if "enabled" in telemetry and telemetry["enabled"] != defaults.enable_telemetry:
        return True

    # routing.routing_strategy
    routing = doc.get("routing", {})
    if "routing_strategy" in routing and routing["routing_strategy"] != config_defaults.routing_strategy:
        return True

    # logging.format
    logging_section = doc.get("logging", {})
    if "format" in logging_section and logging_section["format"] != config_defaults.log_format:
        return True

    return False


def _assert_features_persisted(cfg: SearchConfig, features: WizardFeatures) -> None:
    """Verify the wizard's HyDE / RAG Fusion choices survived the config round-trip.

    Called in ``run()`` immediately after the freshly-written config is reloaded
    via ``load_config``. Surfaces a silent write/parse failure at install time —
    with an actionable message — instead of letting a feature show as enabled in
    the wizard but disabled on the server. Raises ``InstallError`` on mismatch.
    """
    if features.enable_hyde and not cfg.hyde.enabled:
        raise InstallError(
            "[hyde].enabled was requested but is not present in the written "
            "archon-search.toml after reload — the config write did not persist. "
            "This is a bug; please re-run the wizard and report it if it recurs."
        )
    if features.enable_rag_fusion and not cfg.rag_fusion.enabled:
        raise InstallError(
            "[rag_fusion].enabled was requested but is not present in the written "
            "archon-search.toml after reload — the config write did not persist. "
            "This is a bug; please re-run the wizard and report it if it recurs."
        )


def _revert_graph_enabled_flag(config_path: Path, dry_run: bool) -> None:
    """Revert ``graph.enabled`` to false in the written config.

    ``run()`` writes ``graph.enabled=true`` early (config-write branches)
    whenever ``features.install_graph_extra`` is set, before the ``[graph]``
    extras are actually installed. If a later step aborts or fails before
    that install succeeds, leaving ``graph.enabled=true`` on disk would
    hard-fail the next server start via app.py's ``_check_graph_deps`` (spaCy
    absent) — strictly worse than BE-11's soft-degrade goal. Call this at
    every such early-return point (C3-A-1 fix).
    """
    if dry_run or not config_path.exists():
        return
    doc = tomlkit.parse(config_path.read_text())
    if "graph" in doc and "enabled" in doc["graph"]:
        doc["graph"]["enabled"] = False
        atomic_write_bytes(config_path, tomlkit.dumps(doc).encode())
        print(
            "Warning: graph.enabled has been reverted to false because "
            "the install did not complete; re-run the wizard or install "
            "archon-search[graph] manually to enable code/prose graphing.",
            file=sys.stderr,
        )


def _revert_multilingual_flag(config_path: Path, dry_run: bool) -> None:
    """Revert ``[database].multilingual`` to false in the written config.

    ``run()`` writes ``multilingual=true`` early (config-write branches, Step
    6/7/8) whenever a multilingual profile is selected, before the
    ``[multilingual]`` extra is installed. If a later step aborts or fails
    before that install succeeds, leaving ``multilingual=true`` on disk would
    hard-fail the next server start via app.py's ``_check_multilingual_deps``
    (fasttext-wheel absent). Reverting lets the server start English-only
    instead of crashing. Mirrors :func:`_revert_graph_enabled_flag`. Note the
    ``multilingual=true`` flag reverted here is written by the profile config
    writer (``_write_profile_config``/``_profile_toml``), NOT by the
    ``_apply_wizard_features_to_toml`` overlay that the graph flag comes from.
    """
    if dry_run or not config_path.exists():
        return
    doc = tomlkit.parse(config_path.read_text())
    if "database" in doc and "multilingual" in doc["database"]:
        doc["database"]["multilingual"] = False
        atomic_write_bytes(config_path, tomlkit.dumps(doc).encode())
        print(
            "Warning: multilingual has been reverted to false because the "
            "install did not complete; the server will start in English-only "
            "mode. Re-run the wizard or install archon-search[multilingual] "
            "manually to enable multilingual language detection.",
            file=sys.stderr,
        )
