"""macOS LaunchdSearchService — manages archon_search.server as a launchd daemon."""
from __future__ import annotations

import logging
import re
import subprocess
import sys
from pathlib import Path

from archon_search.platform.service import SearchServiceLifecycle, ServiceStatus

log = logging.getLogger(__name__)

_LABEL = "com.archon.search"

_PLIST_TEMPLATE = """\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/sbin/taskpolicy</string>
        <string>-b</string>
        <string>{wrapper_script}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>{cwd}</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>ARCHON_SEARCH_CONFIG</key>
        <string>{config_path}</string>
    </dict>
    <key>StandardOutPath</key>
    <string>{log_path}</string>
    <key>StandardErrorPath</key>
    <string>{log_path}</string>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>60</integer>
</dict>
</plist>
"""

_WRAPPER_SCRIPT_TEMPLATE = """\
#!/bin/sh
# Auto-generated by archon-search. Do not edit.
[ -f "{secrets_file}" ] && {{ set -a; . "{secrets_file}"; set +a; }}
exec "{python}" -m archon_search.server
"""


class LaunchdSearchService(SearchServiceLifecycle):
    """Manages the archon-search server as a macOS launchd user agent."""

    @property
    def _plist_path(self) -> Path:
        return Path.home() / "Library" / "LaunchAgents" / "com.archon.search.plist"

    def _run(self, cmd: list[str]) -> subprocess.CompletedProcess[str]:
        return subprocess.run(cmd, capture_output=True, text=True)

    def _is_loaded(self) -> bool:
        try:
            result = self._run(["launchctl", "list", _LABEL])
            return result.returncode == 0
        except FileNotFoundError:
            return False

    def register(self, dry_run: bool = False) -> None:
        data_dir = Path.home() / ".archon-search"
        cwd = str(data_dir)
        config_path = str(data_dir / "archon-search.toml")
        log_path = str(data_dir / "logs" / "archon-search.log")
        wrapper_path = data_dir / "run-server.sh"
        secrets_file = str(data_dir / ".secrets.env")

        if dry_run:
            return

        wrapper_content = _WRAPPER_SCRIPT_TEMPLATE.format(
            secrets_file=secrets_file,
            python=sys.executable,
        )

        content = _PLIST_TEMPLATE.format(
            label=_LABEL,
            wrapper_script=str(wrapper_path),
            cwd=cwd,
            config_path=config_path,
            log_path=log_path,
        )

        try:
            data_dir.mkdir(parents=True, exist_ok=True)
            wrapper_path.write_text(wrapper_content)  # noqa: durable-write
            wrapper_path.chmod(0o755)
            self._plist_path.parent.mkdir(parents=True, exist_ok=True)
            Path(log_path).parent.mkdir(parents=True, exist_ok=True)
            self._plist_path.write_text(content)  # noqa: durable-write
        except PermissionError as e:
            raise RuntimeError(f"Permission denied writing service files in {data_dir}") from e

    def unregister(self, dry_run: bool = False) -> None:
        if dry_run:
            return
        if self._is_loaded():
            try:
                result = self._run(["launchctl", "unload", str(self._plist_path)])
                if result.returncode != 0:
                    log.warning("launchctl unload failed (rc=%d): %s", result.returncode, result.stderr)
            except FileNotFoundError as exc:
                raise RuntimeError("launchctl binary not found") from exc
        if self._plist_path.exists():
            self._plist_path.unlink()
        wrapper = Path.home() / ".archon-search" / "run-server.sh"
        wrapper.unlink(missing_ok=True)

    def start(self, dry_run: bool = False) -> int:
        if dry_run:
            return 0
        if not self._plist_path.exists():
            raise RuntimeError(f"Plist not installed at {self._plist_path}")
        if self._is_loaded():
            return 0
        try:
            r1 = self._run(["launchctl", "load", str(self._plist_path)])
            if r1.returncode != 0:
                raise RuntimeError(f"launchctl load failed (rc={r1.returncode}): {r1.stderr}")
            r2 = self._run(["launchctl", "start", _LABEL])
            if r2.returncode != 0:
                raise RuntimeError(f"launchctl start failed (rc={r2.returncode}): {r2.stderr}")
        except FileNotFoundError as exc:
            raise RuntimeError("launchctl binary not found") from exc
        return 0

    def stop(self, dry_run: bool = False) -> int:
        if dry_run:
            return 0
        if not self._is_loaded():
            return 0
        try:
            result = self._run(["launchctl", "unload", str(self._plist_path)])
            if result.returncode != 0:
                raise RuntimeError(f"launchctl unload failed (rc={result.returncode}): {result.stderr}")
        except FileNotFoundError as exc:
            raise RuntimeError("launchctl binary not found") from exc
        return 0

    def status(self) -> ServiceStatus:
        try:
            result = self._run(["launchctl", "list", _LABEL])
        except FileNotFoundError:
            return ServiceStatus(running=False, pid=None, uptime_seconds=None)

        if result.returncode != 0:
            return ServiceStatus(running=False, pid=None, uptime_seconds=None)

        pid_match = re.search(r'"PID"\s*=\s*(\d+)', result.stdout)
        if not pid_match:
            return ServiceStatus(running=False, pid=None, uptime_seconds=None)

        try:
            pid = int(pid_match.group(1))
        except ValueError:
            return ServiceStatus(running=False, pid=None, uptime_seconds=None)

        if pid == 0:
            return ServiceStatus(running=False, pid=0, uptime_seconds=None)

        return ServiceStatus(running=True, pid=pid, uptime_seconds=None)
